---
classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../README.md"
        title: "Setup"
      - file: "../exercises/1-creating-components.md"
        title: "Creating components"
      - file: "../exercises/2-databinding.md"
        title: "Practicing data-binding"
      - file: "../exercises/3-directives.md"
        title: "Practicing directives"
      - file: "../exercises/4-Sample-App-1st-part.md"
        title: "Course Project Part 1"
      - file: "../exercises/5-Sample-App-part2.md"
        title: "Course Project Part 2"
