---
classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../README.md"
        title: "Setup"
      - file: "../exercises/1-creating-components.md"
        title: "Creating components"
      - file: "../exercises/2-databinding.md"
        title: "Practicing data-binding"
      - file: "../exercises/3-directives.md"
        title: "Practicing directives"